/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 scene.gltf 
Author: T.Koeniger (https://sketchfab.com/3D-hannover)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/buddha-four-faces-18405445c05e48fabbc915d69ae2ccc2
Title: Buddha - Four Faces
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -1.897, -1.284]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          // material={materials.material_0}
        >
          <meshPhongMaterial opacity={0} transparent />
        </mesh>
        <mesh
        // geometry={nodes.Object_3.geometry}
        // material={materials.material_0}
        />
        <mesh
        // geometry={nodes.Object_4.geometry}
        // material={materials.material_0}
        />
        <mesh
        // geometry={nodes.Object_5.geometry}
        // material={materials.material_0}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
