import Play from '@/components/Playlist'
import readFileContent from '@/utils/readfile'
import fs from 'fs'
import { GetStaticPaths, GetStaticProps, InferGetStaticPropsType } from 'next'
import Head from 'next/head'
import path from 'path'
import { ParsedUrlQuery } from 'querystring'

function PlayDetailPage({
  content,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  console.log(content)

  return (
    <>
      <Head>
        <title>P L A Y</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {content && <Play.Detail content={content} />}
    </>
  )
}

export const getStaticPaths = (async () => {
  const files = fs
    .readdirSync(path.join('constants/playlist'))
    .filter((file) => file !== '.DS_Store')

  return {
    paths: files.map((file) => ({
      params: { id: file.replace('.json', '').replace('Dongha Radio ', '') },
    })),
    fallback: true, // false or "blocking"
  }
}) satisfies GetStaticPaths

export const getStaticProps: GetStaticProps = async ({ params }) => {
  const { id } = params as ParsedUrlQuery

  const fileContent: string = (await readFileContent(
    `constants/playlist/Dongha Radio ${id}.json`,
  )) as string

  return {
    props: {
      content: fileContent,
    },
  }
}

export default PlayDetailPage
