import fs from 'fs'
import path from 'path'

import Play from '@/components/Playlist'
import { GetStaticProps, InferGetStaticPropsType } from 'next'
import Head from 'next/head'

function PlaylistPage({
  list,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <>
      <Head>
        <title>P L A Y</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Play.List list={list} />
    </>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const files = fs
    .readdirSync(path.join('constants/playlist'))
    .filter((file) => file !== '.DS_Store')

  return {
    props: {
      list: files
        .map((file: string) => file.replace('.json', ''))
        .sort((a, b) => {
          const A = a.replace('Dongha Radio ', '')
          const B = b.replace('Dongha Radio ', '')
          return +A - +B
        })
        .reverse(),
    },
  }
}

export default PlaylistPage
