/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { forwardRef } from "react";
import { useGLTF } from "@react-three/drei";
import { MetalMaterial } from "./MetalMaterial";

function Model(props, ref) {
  const { nodes } = useGLTF("obj/macbook.gltf");

  return (
    <mesh
      ref={ref}
      {...props}
      dispose={null}
      geometry={nodes.Object_4001.geometry}
      material={nodes.Object_4001.material}
      scale={3.53}
    >
      <meshPhongMaterial color={props.color} />
    </mesh>
  );
}

export default forwardRef(Model);

useGLTF.preload("obj/macbook.gltf");
