/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei"
import { forwardRef } from "react"

const Model = forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF("obj/headphone.gltf")

  return (
    <mesh
      ref={ref}
      dispose={null}
      geometry={nodes.Skullcandy_Crusher_M_Skullcandy_Crusher_0.geometry}
      material={materials["Material.001"]}
      scale={0.3}
      {...props}
    >
      <meshPhongMaterial color={props.color} />
    </mesh>
  )
})

useGLTF.preload("obj/headphone.gltf")

Model.displayName = "Headphone"

export default Model
