/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { forwardRef } from "react";
import { useGLTF } from "@react-three/drei";
import { MeshProps } from "@react-three/fiber";
import { ObjectInterface } from "../../@types/interface";

const Model = forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF("obj/keyboard.gltf");
  return (
    <mesh
      ref={ref}
      dispose={null}
      geometry={nodes.Keycaps_Keycaps_0001.geometry}
      material={materials["Material.002"]}
      scale={0.18}
      {...props}
    >
      <meshPhongMaterial color={props.color} />
    </mesh>
  );
});

useGLTF.preload("obj/keyboard.gltf");
Model.displayName = "Keyboard"

export default Model;
