/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { useCompoundBody } from "@react-three/cannon";
import { MeshProps } from "@react-three/fiber";
import { ObjectInterface } from "../../@types/interface";
import { forwardRef } from "react";

const Model = forwardRef<ObjectInterface, MeshProps>((props, ref) => {
  const { nodes, materials } = useGLTF("obj/macbook.gltf");

  return (
    <mesh
      ref={ref}
      dispose={null}
      geometry={nodes.Object_4001.geometry}
      material={nodes.Object_4001.material}
      scale={3.53}
    >
      <meshPhongMaterial color={props.color} />
    </mesh>
  );
});

useGLTF.preload("obj/macbook.gltf");

export default Model;
