/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei"
import { forwardRef } from "react"

const Model = forwardRef((props, ref) => {
  const { nodes } = useGLTF("obj/macbook.gltf")

  return (
    <mesh
      ref={ref}
      dispose={null}
      geometry={nodes.Object_4001.geometry}
      material={nodes.Object_4001.material}
      scale={3.53}
      {...props}
    >
      <meshPhongMaterial color={props.color} />
    </mesh>
  )
})

useGLTF.preload("obj/macbook.gltf")
Model.displayName = "Macbook"

export default Model
