/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/contact.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Mesh_14.geometry}
        material={nodes.Mesh_14.material}
        position={[-0.04, 1.77, 3.41]}
        rotation={[0.92, 0.16, 0.78]}
        scale={0.31}
      />
    </group>
  )
}

useGLTF.preload('/contact.gltf')
