/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, forwardRef } from "react";
import { useThree, useFrame } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";

function Model(props, ref) {
  const { nodes, materials } = useGLTF("/keyboard.gltf");
  console.log(props);
  return (
    <mesh
      ref={ref}
      {...props}
      dispose={null}
      geometry={nodes.Keycaps_Keycaps_0001.geometry}
      material={materials["Material.002"]}
      scale={0.18}
    >
      <meshPhongMaterial color={props.color} />
    </mesh>
  );
}

useGLTF.preload("/keyboard.gltf");

export default forwardRef(Model);
