/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: suvorova.lena484 (https://sketchfab.com/suvorova.lena484)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/course-project-draft-boom-box-fa29e9e0038e4206948d2037a58b138e
title: Course project draft/ Boom-box
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/boombox.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, -3, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials['6_setka']} geometry={nodes.mesh_0.geometry} >
        <meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={0.2}
          />

        </mesh>
        <mesh material={materials.Material} geometry={nodes.mesh_6.geometry} >
        <meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={0.2}
          />
        </mesh>
        <mesh material={materials['Material.001']} geometry={nodes.mesh_7.geometry} >
        <meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={0.2}
          />
        </mesh>
        <mesh material={materials['null']} geometry={nodes.mesh_8.geometry} >
        <meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={0.2}
          />
        </mesh>
        <mesh material={materials['1_panel']} geometry={nodes.mesh_9.geometry} >
        <meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={0.2}
          />
        </mesh>
        <mesh material={materials['1_panel.001']} geometry={nodes.mesh_10.geometry} >
        <meshStandardMaterial
            attach="material"
            color="#dddddd"
            roughness={0.3}
            metalness={0.2}
          />
        </mesh>
        <mesh material={materials.material} geometry={nodes.mesh_11.geometry} >
          <meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={0.2}
          />
        </mesh>

        <mesh material={materials['3_radio']} geometry={nodes.mesh_12.geometry} >
        <meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={0.2}
          />
        </mesh>
        <mesh material={materials['4_matovii']} geometry={nodes.mesh_13.geometry} >
        <meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={0.2}
          />
        </mesh>
        <lineSegments material={materials['6_setka']} geometry={nodes.mesh_14.geometry} />
        <mesh material={materials['6_setka']} geometry={nodes.mesh_15.geometry} >
        <meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={0.2}
          />
        </mesh>
        <mesh material={materials['6_setka']} geometry={nodes.mesh_16.geometry} >
        <meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={0.2}
          />
        </mesh>
        <mesh material={materials.Crome} geometry={nodes.mesh_17.geometry} >
        <meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={0.2}
          />
        </mesh>
        <mesh material={materials.Fake_Glass} geometry={nodes.mesh_18.geometry} >
        <meshStandardMaterial
            attach="material"
            color="#fcfcfc"
            roughness={0.3}
            metalness={0.2}
          />
        </mesh>
        <mesh material={materials.Fake_Glass} geometry={nodes.mesh_19.geometry} >
        <meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={0.2}
          />
        </mesh>
        <mesh material={materials.Fake_Glass} geometry={nodes.mesh_20.geometry} >
        <meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={0.2}
          />
        </mesh>
        <mesh material={materials.Fake_Glass} geometry={nodes.mesh_21.geometry} >
        <meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={0.2}
          />
        </mesh>
        <mesh material={materials.Fake_Glass} geometry={nodes.mesh_22.geometry} >
        <meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={0.2}
          />
        </mesh>
        <mesh material={materials.Fake_Glass} geometry={nodes.mesh_23.geometry} >
        <meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={0.2}
          />
        </mesh>
        <mesh material={materials.Fake_Glass} geometry={nodes.mesh_24.geometry} >
        <meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={0.2}
          />
        </mesh>
        <mesh material={materials.Rele} geometry={nodes.mesh_50.geometry} >
        <meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={0.2}
          />
        </mesh>
        <mesh material={materials.Rele} geometry={nodes.mesh_51.geometry} >
        <meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={0.2}
          />
        </mesh>
        <mesh material={materials.Rele} geometry={nodes.mesh_52.geometry} >
        <meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={0.2}
          />
        </mesh>
        <mesh material={materials.Rele} geometry={nodes.mesh_53.geometry} >
        <meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={0.2}
          />
        </mesh>
        <mesh material={materials.Rele} geometry={nodes.mesh_54.geometry} >
        <meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={0.2}
          />
        </mesh>
        <mesh material={materials.Rele} geometry={nodes.mesh_55.geometry} >
        <meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={0.2}
          />
        </mesh>
        <mesh material={materials.Rele} geometry={nodes.mesh_56.geometry} >
        <meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={0.2}
          />
        </mesh>
        <mesh material={materials.Rele} geometry={nodes.mesh_57.geometry} >
        <meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={0.2}
          />
        </mesh>
        <mesh material={materials.Rele} geometry={nodes.mesh_58.geometry} >
        <meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={0.2}
          />
        </mesh>
        <mesh material={materials.Rele} geometry={nodes.mesh_59.geometry} >
        <meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={0.2}
          />
        </mesh>
        <mesh material={materials.Rele} geometry={nodes.mesh_60.geometry} >
        <meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={0.2}
          />
        </mesh>
        <mesh material={materials.Rele} geometry={nodes.mesh_61.geometry} >
        <meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={0.2}
          />
        </mesh>
        <mesh material={materials.Rele} geometry={nodes.mesh_62.geometry} >
        <meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={0.2}
          />
        </mesh>
        <mesh material={materials.Rele} geometry={nodes.mesh_63.geometry} >
        <meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={0.2}
          />
        </mesh>
        <mesh material={materials.knopki} geometry={nodes.mesh_64.geometry} >
        <meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={0.2}
          />
        </mesh>
        <mesh material={materials.pereklushatel} geometry={nodes.mesh_65.geometry} >
        <meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={0.2}
          />
        </mesh>
        <mesh material={materials.reika} geometry={nodes.mesh_66.geometry} >
        <meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={0.2}
          />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/boombox.gltf')
