/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Alexis (https://sketchfab.com/alexis.martinho1)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/f8a1e5cd151842a9b098692a4e4653b0
title: Hamburger
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/burger.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_0.geometry} />
        <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_1.geometry} />
        <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_2.geometry} />
        <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_3.geometry} />
        <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_4.geometry} />
        <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_5.geometry} />
        <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_6.geometry} />
        <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_7.geometry} />
        <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_8.geometry} />
        <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_9.geometry} />
        <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_10.geometry} />
        <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_11.geometry} />
        <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_12.geometry} />
        <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_13.geometry} />
        <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_14.geometry} />
        <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_15.geometry} />
        <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_16.geometry} />
        <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_17.geometry} />
        <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_18.geometry} />
        <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_19.geometry} />
        <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_20.geometry} />
        <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_21.geometry} />
        <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_22.geometry} />
        <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_23.geometry} />
        <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_24.geometry} />
        <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_25.geometry} />
        <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_26.geometry} />
        <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_27.geometry} />
        <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_28.geometry} />
        <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_29.geometry} />
        <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_30.geometry} />
        <mesh material={materials['Scene_-_Root']} geometry={nodes.mesh_31.geometry} />
      </group>
    </group>
  )
}

useGLTF.preload('/burger.gltf')
