/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: mena3d (https://sketchfab.com/mena3d)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/burger-1-b513bb039fa04a3a98ea8d5b5cf23891
title: Burger 1
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/burger.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[20, 0, 10]}>
        <group position={[3.5, -5, 54]} rotation={[-Math.PI / 2, 0, 0]} scale={[8, 8, 8]}>
          <mesh material={materials.defaultMat} geometry={nodes.mesh_0.geometry} >
            <meshStandardMaterial
              attach="material"
              color="white"
              roughness={0.3}
              metalness={0.2}
            />
          </mesh>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/burger.gltf')
