/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Daniel O'Neil (https://sketchfab.com/doneil)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/3b66e98d137d4a23aaa725ce0a8aec28
title: Macintosh Classic (1991)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Mac(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/mac.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[20, 0, 10]}>
        <group position={[-4.7, 0, 0]} scale={[.01, .01, .01]}>
          <mesh material={
            materials['Mac.Tri.Baked']}
            geometry={nodes.Mac_Tri_Baked_MacTriBaked_0.geometry}
          >
            <meshStandardMaterial
              attach="material"
              color="white"
              roughness={0.3}
              metalness={0.2} />
          </mesh>
        </group>
      </group >
    </group>
  )
}

useGLTF.preload('/mac.gltf')
