/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: WeaZy (https://sketchfab.com/WeaZy)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/de1283e3b23a4fd5aa2e9932c78eba39
title: Record Player
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/record.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0,-4,-12]} scale={[2,2,2]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.75, 0, 1.27]} />
          <group position={[0, 0, -1000.1]} rotation={[0, -Math.PI / 2, 0]} />
          <group position={[4.03, 0.09, 0.07]} rotation={[0.02, -0.72, 0.01]}>
            <mesh material={materials.naald} geometry={nodes.polySurface1_naald_0.geometry}>
              <meshStandardMaterial
                attach="material"
                color="white"
                roughness={0.3}
                metalness={0.2}
              />
            </mesh>
          </group>
          <mesh material={materials.stand} geometry={nodes.Opbouw3_stand_0.geometry} >
            <meshStandardMaterial
              attach="material"
              color="white"
              roughness={0.3}
              metalness={0.2}
            />
          </mesh>
          <mesh material={materials.aiStandardSurface7} geometry={nodes.polySurface4_aiStandardSurface7_0.geometry} >
            <meshStandardMaterial
              attach="material"
              color="white"
              roughness={0.3}
              metalness={0.2}
            />
          </mesh>
          <mesh material={materials.ijzer} geometry={nodes.Hendelhouder_4_ijzer_0.geometry} >
            <meshStandardMaterial
              attach="material"
              color="white"
              roughness={0.3}
              metalness={0.2}
            />
          </mesh>
          <group position={[-3.05, 0, 6.68]} rotation={[-Math.PI, -0.03, -Math.PI]} scale={[0.04, 0.55, 1.02]}>
            <mesh material={materials.box_R} geometry={nodes.Boxen1_box_R_0.geometry} >
              <meshStandardMaterial
                attach="material"
                color="white"
                roughness={0.3}
                metalness={0.2}
              />
            </mesh>
          </group>
          <mesh material={materials.onder} geometry={nodes.pCylinder19_onder_0.geometry} ><meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={0.2}
          /></mesh>
          <mesh material={materials.outputs} geometry={nodes.pCylinder32_outputs_0.geometry} ><meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={0.2}
          /></mesh>
          <group position={[-0.92, 0.66, 6.72]} scale={[2.1, 2.1, 2.1]}>
            <mesh material={materials.plaat1} geometry={nodes.pDisc1_plaat1_0.geometry} >
              <meshStandardMaterial
                attach="material"
                color="white"
                roughness={0.3}
                metalness={0.2}
              />
            </mesh>
          </group>
          <mesh material={materials.lampjes} geometry={nodes.pSphere8_lampjes_0.geometry} >
            <meshStandardMaterial
              attach="material"
              color="white"
              roughness={0.3}
              metalness={0.2}
            />
          </mesh>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/record.gltf')
