/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: WeaZy (https://sketchfab.com/WeaZy)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/de1283e3b23a4fd5aa2e9932c78eba39
title: Record Player
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Record(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/record.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[3.05, 0, 6.68]} scale={[0.04, 0.55, 1.02]}>
            <group position={[-85.8, -0.39, 2.12]} scale={[55.29, 0.54, 0.16]}>
              <mesh material={materials.hendel} geometry={nodes.pCube12_hendel_0.geometry} />
            </group>
            <mesh material={materials.box_R} geometry={nodes.Boxen_box_R_0.geometry} />
          </group>
          <group position={[2.4, -0.56, 5.15]} scale={[0.18, 0.18, 0.18]}>
            <group position={[-27.36, 0, 0]}>
              <mesh material={materials.zwart} geometry={nodes.pCylinder17_zwart_0.geometry} />
            </group>
            <group position={[-27.36, 0, 17.72]}>
              <mesh material={materials.zwart} geometry={nodes.pCylinder18_zwart_0.geometry} />
            </group>
            <group position={[0, 0, 17.72]}>
              <mesh material={materials.zwart} geometry={nodes.pCylinder1_zwart_0.geometry} />
            </group>
            <mesh material={materials.zwart} geometry={nodes.Ondersteuntjes_zwart_0.geometry} />
          </group>
          <group position={[0, 3.82, 5.7]} rotation={[Math.PI / 2, 0, 0.91]} scale={[1, 1, 1]}>
            <group rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <group position={[0, 0, 7.24]}>
            <group rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <group position={[-1000.13, 0.73, 7.3]} rotation={[0, 0, 0]} />
          <group position={[2.58, 0.59, 7.28]} scale={[0.15, 0.11, 0.15]}>
            <mesh material={materials.volume} geometry={nodes.Volume_volume_0.geometry} />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]} />
          <group position={[-0.75, 0, 1.27]}>
            <group position={[2.67, 0.47, 7.85]} scale={[0.04, 0.06, 0.07]}>
              <mesh material={materials.inputs} geometry={nodes.pTorus6_inputs_0.geometry} />
            </group>
            <group position={[2.67, 0.47, 7.63]} scale={[0.04, 0.06, 0.07]}>
              <mesh material={materials.inputs} geometry={nodes.pTorus5_inputs_0.geometry} />
            </group>
            <group position={[2.51, 0.47, 7.63]} scale={[0.04, 0.06, 0.07]}>
              <mesh material={materials.inputs} geometry={nodes.pTorus4_inputs_0.geometry} />
            </group>
            <group position={[2.34, 0.47, 7.63]} scale={[0.04, 0.06, 0.07]}>
              <mesh material={materials.inputs} geometry={nodes.pTorus3_inputs_0.geometry} />
            </group>
            <group position={[2.34, 0.47, 7.85]} scale={[0.04, 0.06, 0.07]}>
              <mesh material={materials.inputs} geometry={nodes.pTorus2_inputs_0.geometry} />
            </group>
            <group position={[2.51, 0.47, 7.85]} scale={[0.04, 0.06, 0.07]}>
              <mesh material={materials.inputs} geometry={nodes.pTorus1_inputs_0.geometry} />
            </group>
            <mesh material={materials.inputs} geometry={nodes.Inputs_inputs_0.geometry} />
          </group>
          <group position={[2.54, 0.4, 6.95]} scale={[0.03, 0.08, 0.14]}>
            <group position={[1.02, 0, 0]}>
              <mesh material={materials.lambert1} geometry={nodes.pCube26_lambert1_0.geometry} />
            </group>
            <group position={[-1.46, 0, 0]}>
              <mesh material={materials.lambert1} geometry={nodes.pCube27_lambert1_0.geometry} />
            </group>
            <group position={[-0.27, 0, -0.55]} rotation={[0, Math.PI / 2, 0]}>
              <mesh material={materials.lambert1} geometry={nodes.pCube28_lambert1_0.geometry} />
            </group>
            <group position={[-0.27, 0, 0.54]} rotation={[0, Math.PI / 2, 0]}>
              <mesh material={materials.lambert1} geometry={nodes.pCube29_lambert1_0.geometry} />
            </group>
            <mesh material={materials.lambert1} geometry={nodes.Usb_inport_lambert1_0.geometry} />
          </group>
          <group position={[-0.92, 0.56, 6.73]} scale={[1.61, 0.07, 1.61]}>
            <group position={[0, 1.22, 0]} scale={[0.02, 1.07, 0.02]}>
              <mesh
                material={materials.aiStandardSurface14}
                geometry={nodes.Middelstuk_plaat_aiStandardSurface14_0.geometry}
              />
            </group>
            <mesh material={materials.lp_drager} geometry={nodes.Platen_houder_lp_drager_0.geometry} />
          </group>
          <group position={[0, 0, -1000.1]} rotation={[0, -Math.PI / 2, 0]} />
          <group position={[4.03, 0.09, 0.07]} rotation={[0.02, -0.72, 0.01]}>
            <mesh material={materials.naald} geometry={nodes.polySurface1_naald_0.geometry} />
          </group>
          <mesh material={materials.stand} geometry={nodes.Opbouw3_stand_0.geometry} />
          <mesh material={materials.aiStandardSurface7} geometry={nodes.polySurface4_aiStandardSurface7_0.geometry} />
          <mesh material={materials.ijzer} geometry={nodes.Hendelhouder_4_ijzer_0.geometry} />
          <group position={[-3.05, 0, 6.68]} rotation={[-Math.PI, -0.03, -Math.PI]} scale={[0.04, 0.55, 1.02]}>
            <mesh material={materials.box_R} geometry={nodes.Boxen1_box_R_0.geometry} />
          </group>
          <mesh material={materials.onder} geometry={nodes.pCylinder19_onder_0.geometry} />
          <mesh material={materials.outputs} geometry={nodes.pCylinder32_outputs_0.geometry} />
          <group position={[-0.92, 0.66, 6.72]} scale={[2.1, 2.1, 2.1]}>
            <mesh material={materials.plaat1} geometry={nodes.pDisc1_plaat1_0.geometry} />
          </group>
          <mesh material={materials.lampjes} geometry={nodes.pSphere8_lampjes_0.geometry} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/record.gltf')
