/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: The British Museum (https://sketchfab.com/britishmuseum)
license: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
source: https://sketchfab.com/models/62886082c3b144d18ca516b396cf29f5
title: Antinous
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from "react-three-fiber";

export default function Statue(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/statue.gltf')
  useFrame(() => {
    // group.current.rotation.y += 0.01;
  });


  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-4, 6.8, 8]} rotation={[-Math.PI / 2, Math.PI / 2, Math.PI/8]}>
        <mesh castShadow material={materials.material_0} geometry={nodes.mesh_0.geometry}>
          <meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={0.2}
          />
        </mesh>
        <mesh castShadow material={materials.material_0} geometry={nodes.mesh_1.geometry} >
          <meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={0.2}
          />
        </mesh>
        <mesh castShadow material={materials.material_0} geometry={nodes.mesh_2.geometry} >
          <meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={0.2}
          />
        </mesh>
        <mesh castShadow material={materials.material_0} geometry={nodes.mesh_3.geometry} >
          <meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={0.2}
          />
        </mesh>
        <mesh castShadow material={materials.material_0} geometry={nodes.mesh_4.geometry} >
          <meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={0.2}
          />
        </mesh>
        <mesh castShadow material={materials.material_0} geometry={nodes.mesh_5.geometry} >
          <meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={0.2}
          />
        </mesh>
        <mesh castShadow material={materials.material_0} geometry={nodes.mesh_6.geometry} >
          <meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={0.2}
          />
        </mesh>
        <mesh castShadow material={materials.material_0} geometry={nodes.mesh_7.geometry} >
          <meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={0.2}
          />
        </mesh>
        <mesh castShadow material={materials.material_0} geometry={nodes.mesh_8.geometry} >
          <meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={0.2}
          />
        </mesh>
        <mesh castShadow material={materials.material_0} geometry={nodes.mesh_9.geometry} >
          <meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={0.2}
          />
        </mesh>
        <mesh castShadow material={materials.material_0} geometry={nodes.mesh_10.geometry} >
          <meshStandardMaterial
            attach="material"
            color="white"
            roughness={0.3}
            metalness={0.2}
          />
        </mesh>
      </group>

    </group>
  )
}

useGLTF.preload('/statue.gltf')
