import Space from '@/components/Space'
import Head from 'next/head'
import React from 'react'

function SpacePage() {
  return (
    <>
      <Head>
        <title>S P A C E</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          width: '100vw',
          height: '100vh',
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
        }}
      >
        NO SPACE AT THIS MOMENT
      </div>
      {/* <Space.List /> */}
    </>
  )
}

export default SpacePage
