import HomeContainer from '@/components/Home'
import Head from 'next/head'

function HomePage() {
  return (
    <>
      <Head>
        <title>D O N G H A K A N G</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeContainer />
    </>
  )
}

export default HomePage
